name: Jest

on:
  push:
    branches:
      - main
      - test_ci

defaults:
  run:
    shell: bash
    working-directory: src/backend

jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm

      - name: Run tests
        env:
          RESAS_API_KEY: $ {{ secrets.RESAS_API_KEY }}
        run: npm test